apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: d8s6aowto-python 
  janus-idp.io/tekton: d8s6aowto-python
  backstage.io/kubernetes-id: d8s6aowto-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d8s6aowto-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  