apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: d8s6aowto-python
  janus-idp.io/tekton: d8s6aowto-python
  backstage.io/kubernetes-id: d8s6aowto-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d8s6aowto-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
