apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: d8s6aowto-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: d8s6aowto-python 
  name: d8s6aowto-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: d8s6aowto-python 
